### PR TITLE
Paragon reputation workaround (Issue 22)

### PR DESCRIPTION
**Pull request by cristamd**
Added the workaround to the end of the function as suggested by MuffinManKen on Issue 22. Even if this doesn't get merged, others can clone or download the file from the pull request to get the necessary change more easily.

### CODE REVIEW

**Comment by fizzwidget** [comment]
tweaked the messaging a bit on top of this. Thanks!

**Comment by Enigma-TL** [comment]
So how do we get the new file? Am new to github?

**Comment by fizzwidget** [comment]
I'll be posting a new release with this and a few other changes shortly. Until then you're welcome to grab [the raw FactionFriend.lua file from GitHub ](https://github.com/fizzwidget/faction-friend/raw/master/FactionFriend.lua) and drop it into your existing FF install.

**Comment by Enigma-TL** [comment]
Thanks got the update on Wowinterface. I not sure what I did wrong. I made the changes to the file but still got the nil error. FF Still seemed to work fine.

**Pull request merged**
